
$ Mass Configuration 1
$ Baggage: 100% (0 Kg)
$ Passengers: 100% (6460 Kg)
$ Wing Fuel: 100% (0 Kg)
$ Central Fuel: 100% (0 Kg)
$-------2-------3-------4-------5-------6-------7-------8-------9-------10
$ Lumped masses: PASSENGERS 6460 Kg
$ Fuselage beams: from 2 to 10
$ Fraction of cabin length : from 0 to 100 %
$ Cabin length = 14.752 m.
$-------2-------3-------4-------5-------6-------7-------8-------9-------10
CONM2   284     1002    0       256.147 0       0       0       
        0.      0.      0.      0.      0.      0.      
CONM2   285     1003    0       613.523 0       0       0       
        0.      0.      0.      0.      0.      0.      
CONM2   286     1004    0       487.924 0       0       0       
        0.      0.      0.      0.      0.      0.      
CONM2   287     1005    0       312.87  0       0       0       
        0.      0.      0.      0.      0.      0.      
CONM2   288     1006    0       570.357 0       0       0       
        0.      0.      0.      0.      0.      0.      
CONM2   289     1007    0       738.504 0       0       0       
        0.      0.      0.      0.      0.      0.      
CONM2   290     1008    0       1064.56 0       0       0       
        0.      0.      0.      0.      0.      0.      
CONM2   291     1009    0       1520.13 0       0       0       
        0.      0.      0.      0.      0.      0.      
CONM2   292     1010    0       895.98  0       0       0       
        0.      0.      0.      0.      0.      0.      

$ Summary of payload (as CONM2): 
$ Wing tank: 0
$ Central tank: 0
$ Auxiliary tank: 0
$ Passengers: 6460
$ Baggage: 0
$-------2-------3-------4-------5-------6-------7-------8-------9-------10
$ SUPORT FOR CURRENT CONFIGURATION
SUPORT  1       1006    123456  
$
