function AELINKwriter(fid,AELINK)
fprintf(fid,'%-8s%-8d%-8s%-8s%-8d\n',...
            'AELINK',...
            AELINK.ID,...
            char(AELINK.LABEL1),...
            char(AELINK.LABEL2),...
            AELINK.C1);
end