function AESURFwriter(fid,AESURF)
fprintf(fid,'%8s%8d%8s%8d%8d\n',...
            'AESURF  ',...
            AESURF.ID,...
            AESURF.LABEL,...
            AESURF.CID1,...
            AESURF.ALID1);
end