function CAERO1writer(fid,CAERO1)
fprintf(fid,'%8s%8d%8d%8d%8s%8s%8d%8d%8d\n%8s%8.4f%8.4f%8.4f%8.4f%8.4f%8.4f%8.4f%8.4f\n',...
              'CAERO1  ',CAERO1.EID,...
                         CAERO1.PID,...
                         CAERO1.CP,...
                         '',...
                         '',...
                         CAERO1.LSPAN,...
                         CAERO1.LCHORD,...
                         CAERO1.IGID,...
                         '',...
                         CAERO1.X1,...
                         CAERO1.Y1,...
                         CAERO1.Z1,...
                         CAERO1.X12,...
                         CAERO1.X4,...
                         CAERO1.Y4,...
                         CAERO1.Z4,...
                         CAERO1.X43);
end