function CBARwriter(fid,CBAR)
fprintf(fid,'%8s%8d%8d%8d%8d%8.4f%8.4f%8.4f%8s\n',...
            'CBAR    ',...
            CBAR.EID,...
            CBAR.PID,...
            CBAR.GA ,...
            CBAR.GB ,...
            CBAR.Xi(1),...
            CBAR.Xi(2),...
            CBAR.Xi(3),...
            'GGG');
            %CBAR.OFF);
end