function CBEAMwriter(fid,CBEAM)
fprintf(fid,'%8s%8d%8d%8d%8d%8.4f%8.4f%8.4f\n',...
            'CBEAM   ',...
            CBEAM.EID,...
            CBEAM.PID,...
            CBEAM.GA ,...
            CBEAM.GB ,...
            CBEAM.Xi(1),...
            CBEAM.Xi(2),...
            CBEAM.Xi(3));
end