function CORD2RwriterG(fid,CORD2R)            
fprintf(fid,'%8s%8d%8d%8.4f%8.4f%8.4f%8.4f%8.4f%8.4f\n%8s%8.4f%8.4f%8.4f\n',...
            'CORD2R  ',...
            CORD2R.CID,...
            CORD2R.RID,...
            CORD2R.Ai(1),...
            CORD2R.Ai(2),...
            CORD2R.Ai(3),...
            CORD2R.Bi(1),...
            CORD2R.Bi(2),...
            CORD2R.Bi(3),...
            '',...
            CORD2R.Ci(1),...
            CORD2R.Ci(2),...
            CORD2R.Ci(3));            
end