function GRIDwriter(fid,GRID)
fprintf(fid,'%8s%8d%8d%8.4f%8.4f%8.4f%8d\n',...
            'GRID    ',...
            GRID.ID,...
            GRID.CP,...
            GRID.Xi(1),...
            GRID.Xi(2),...
            GRID.Xi(3),...
            GRID.CD);