function MAT1writer(fid,MAT1)
% '%8s%8d%8s%8s%8.4f%8.0f\n'
fprintf(fid,'%8s%8d%8.2g%8s%8.2g%8.0f\n',...
            'MAT1    ',...
            MAT1.MID,...
            MAT1.E,...     %num2strE(MAT1.E)
            '        ',...
            MAT1.NU,...
            MAT1.RHO);
end