function PBARwriter(fid,PBAR)
%IDs & section's innertial properties 
%--------------1--2--3--4--5--6--7--8--9
fprintf(fid,'%8s%8d%8d%8s%8s%8s%8.3f%8s%8.3f\n',...
            'PBAR    ',...
            PBAR.PID,...
            PBAR.MID,...
            num2strE(PBAR.A),...
                num2strE(PBAR.I1),...
                num2strE(PBAR.I2),...
            PBAR.I12,...   % Pre Modifica num2strE(PBAR.I12)
                num2strE(PBAR.J),...            
            PBAR.NSM);
        
 % Stress recovery points       
 %--------------1----2----3----4----5----6----7----8----9       
 fprintf(fid,'%8s%8.4f%8.4f%8.4f%8.4f%8.4f%8.4f%8.4f%8.4f\n',...
            '',...
            PBAR.C1,...
            PBAR.C2,...
            PBAR.D1,...
            PBAR.D2,...
            PBAR.E1,...
            PBAR.E2,...
            PBAR.F1,...
            PBAR.F2);
     
           
            
end