function SPLINE1writer(fid,SPLINE1)  
fprintf(fid,'%8s%8d%8d%8d%8d%8d\n',...
            'SPLINE1 ',...
            SPLINE1.EID,...
            SPLINE1.CAERO,...
            SPLINE1.BOX1,...
            SPLINE1.BOX2,...
            SPLINE1.SETG);        
end   