$ ============================== Pull-up ===============================
TRIM=   1
$ Max EAS at sea level
TRIM    1       1       0.380   0.0     SIDES   0.0     ROLL    0.0     
        PITCH   0.0     YAW     0.0     URDD2   0.0     THRUST  0.0     
        URDD4   0.0     URDD5   0.0     URDD6   0.0     CLIMB   0.0     
        BANK    0.0     HEAD    0.0     URDD3   24.525  aileronr0       
        rudder1 0       
ITRIM= 1       